title: Hey-What! Documentation
lang: en
description: All the fine details on how to do stuff that took me way to much time to learn but yours for FREE!

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
